version: 0.2
env:
  shell: bash

phases:
  build:
    commands:
      - pulumi login s3://${PULUMI_STATE_S3_BUCKET}
      - cd infra/environment
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f 3) # get feature branch name
      - echo Initialising $BRANCH_NAME stack
      - pulumi stack init $BRANCH_NAME
      - pulumi up --skip-preview
